FROM golang:1.23-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server ./cmd/main.go

FROM build-stage AS run-test-stage
RUN go test -v ./...
RUN go run cmd/migrate/main.go up

FROM scratch AS build-release-stage
WORKDIR /

COPY --from=build-stage /server /server

EXPOSE 8080

ENTRYPOINT ["/server"]