services:
    postgres:
        image: postgres:latest
        container_name: alpha_apartments_local_postgres
        ports:
            - "5432:5432"
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpass
            - POSTGRES_DB=stockdb
            - DATABASE_HOST=localhost
            - DATABASE_PORT=5432
        networks:
            - alpha_apartments_network

networks:
    alpha_apartments_network:


volumes:
    local_postgres_data:
